# Generated by Django 3.1 on 2020-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnosAsignados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('DNI', models.IntegerField()),
                ('Descripcion', models.TextField(max_length=65535)),
                ('ID_Turno_Disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TurnosDisponibles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Doctor', models.CharField(max_length=128)),
                ('Especialidad', models.CharField(max_length=128)),
            ],
        ),
    ]
