# Generated by Django 3.1 on 2020-11-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('DNI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctores.profesor')),
            ],
        ),
    ]
