# Generated by Django 3.1 on 2020-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0005_auto_20201102_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosasignados',
            name='ID_Turno_Disponible',
            field=models.IntegerField(unique=True),
        ),
    ]
