# Generated by Django 3.1 on 2020-11-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctores', '0006_auto_20201112_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
